### PR TITLE
Remove dependencies on deprecated x/tools

### LINKED ISSUE #19: `go get -u sourcegraph.com/sqs/goreturns` fails after `x/tools` deprecation
```bash
lukeh@Lukes-MacBook-Pro:~/dd/temp/go$ go get -u sourcegraph.com/sqs/goreturns
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/Users/lukeh/dd/temp/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
package golang.org/x/tools/go/types: no buildable Go source files in /Users/lukeh/dd/temp/go/src/golang.org/x/tools/go/types
```

This appears to be happening after the change announced here: https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY, and implemented here: https://github.com/golang/tools/commit/adaaa074861b0d254acf51dec74daf7c2ba20e90.

### PR DESCRIPTION
**Pull request by lukehoban**
Update dependencies per
https://groups.google.com/forum/#!topic/golang-announce/qu_rAphYdxY.

Note that this causes `goreturns` to only build on
Go 1.5+.  To support building on Go1.4 likely would require
copying in the previous x/tools sources that are needed.

Fixes #19.

### CODE REVIEW

File: returns/fix_test.go [hunk 1]
```diff
@@ -8,7 +8,7 @@ import (
 	"flag"
 	"testing"
 
-	_ "golang.org/x/tools/go/gcimporter"
+	_ "go/importer"
```
Comment (shurcooL) [inline returns/fix_test.go]: Really minor, but it might be nicer to group `"go/importer"` together with the rest of standard library imports above.

File: goreturns.go [hunk 2]
```diff
@@ -17,9 +17,10 @@ import (
 	"runtime"
 	"strings"
 
-	_ "golang.org/x/tools/go/gcimporter"
 	"golang.org/x/tools/imports"
 
+	_ "go/importer"
```
Comment (shurcooL) [inline goreturns.go]: Here as well.

**Comment by shurcooL** [comment]
Minor comments, LGTM.

**Comment by lukehoban** [comment]
Updated to address @shurcooL comments.
